import { defineProductPattern } from "../product-pattern-definition.ts";

const workspaceRules = {
  primaryProductMode: "axal/workspace" as const,
  copyObligations: ["Name synthetic status, source state, owner, due or review state, blocker, limitation, and next safe action."],
  prohibitedClaims: ["AI finality", "autonomous approval", "autonomous filing or reply", "unsupported reviewed or approved status"],
  reducedMotionBehavior: ["Keep queue order, selected work, evidence, checkpoint, and audit state understandable without animation."],
  forcedColorsBehavior: ["Retain text state, selection outline, panel boundaries, focus, and chronological order using system colors."],
  syntheticRequirement: "Every reference record, entity, source, owner, date, and audit event must be visibly synthetic.",
  consumerResponsibilities: ["Provide authorization, tenant isolation, real sources, persistence, assignment, decision effects, and audit storage."],
} as const;

function accessibilityHooks(semantics: string, focusOrder: string) {
  return {
    semantics,
    keyboard: "Use native links and controls; dense regions remain keyboard reachable with visible focus and labelled overflow.",
    announcements: "Announce changed review, blocker, evidence, or queue status without moving focus or claiming a decision.",
    focusOrder,
  } as const;
}

const trust = [
  "Workspace context may persist only inside the adopter's tenant and authorization boundary.",
  "Generated or extracted content remains a draft until a named human review checkpoint is complete.",
] as const;

const responsive = [
  "Preserve queue, selected work, source evidence, and safe action order when columns collapse.",
  "Dense records may scroll horizontally only inside a labelled, keyboard-focusable region.",
] as const;

const guidance = [
  "Use real workflow labels, owners, due state, source state, and review responsibility.",
  "Keep evidence and audit context visible before approval or progression controls.",
] as const;

export const axalWorkspacePatterns = Object.freeze([
  defineProductPattern({
    name: "ReviewDeskPreview",
    group: "axal-workspace",
    purpose: "Compose a dense review workspace preview with queue, selected work, evidence, and human decision path.",
    ...workspaceRules,
    userJob: "Triage work, inspect the selected record and its sources, then reach a named human decision checkpoint.",
    semanticRoot: "A labelled section containing queue, selected work, evidence, human checkpoint, and audit regions in logical order.",
    intendedProducts: ["axal/workspace", "complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "deskHeader", purpose: "Queue totals and active review context." },
      { name: "syntheticMarker", purpose: "Visible marker that the reference data is synthetic." },
      { name: "workQueue", purpose: "Prioritized review records." },
      { name: "selectedWork", purpose: "Decision, owner, due state, and source state." },
      { name: "evidence", purpose: "Linked sources and uncertainty." },
      { name: "ownerDueReview", purpose: "Named owner, due state, and human review status." },
      { name: "blockedReason", purpose: "Reason progression cannot continue safely." },
      { name: "nextSafeAction", purpose: "Evidence, review, or fallback action." },
      { name: "checkpoint", purpose: "Named human review requirement and safe actions." },
      { name: "auditTrail", purpose: "Recent traceable events." },
    ],
    requiredFields: ["syntheticMarker", "workQueue", "selectedWork", "evidence", "ownerDueReview", "blockedReason", "nextSafeAction", "checkpoint", "auditTrail"],
    variants: [
      { name: "three-pane", purpose: "Queue, selected case, and evidence rail." },
      { name: "stacked", purpose: "Priority-ordered narrow-screen composition." },
    ],
    accessibilityHooks: accessibilityHooks("Use one labelled workspace section with separately labelled queue, selected record, evidence, checkpoint, and audit regions.", "On mobile and desktop, visit queue, selected work, source evidence, human checkpoint, then audit history."),
    states: [
      { name: "ca-review-needed", purpose: "A CA decision is required before progression.", requiredVisibleSignals: ["CA review needed", "selected work", "source state"] },
      { name: "client-input-pending", purpose: "The review waits for named client input.", requiredVisibleSignals: ["client input pending", "requested input", "owner"] },
      { name: "evidence-requested", purpose: "A source or evidence item has been requested.", requiredVisibleSignals: ["evidence requested", "request owner", "next check"] },
      { name: "source-unavailable", purpose: "The authoritative source cannot be opened.", requiredVisibleSignals: ["source unavailable", "reason", "fallback"] },
      { name: "ready-for-reviewer", purpose: "Evidence is ready for the named human reviewer.", requiredVisibleSignals: ["ready for reviewer", "review owner", "source state"] },
      { name: "blocked", purpose: "Evidence or authorization blocks progression.", requiredVisibleSignals: ["blocked", "reason", "resolution owner"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: responsive,
    exemplarRoutes: ["/patterns/axal/", "/lab/axal-review-desk/", "/lab/complyeaze-core/"],
    adopterGuidance: guidance,
    nonGoals: ["full application shell", "filing submission", "autonomous approval"],
  }),
  defineProductPattern({
    name: "EvidencePanel",
    group: "axal-workspace",
    purpose: "Show linked sources, review state, provenance time, uncertainty, and the next safe action.",
    ...workspaceRules,
    userJob: "Inspect available and missing evidence before deciding whether review can continue.",
    semanticRoot: "A labelled aside or section containing a source list, review status, reviewer, checked time, limitation, and safe action.",
    intendedProducts: ["axal/workspace", "tools/local-artifact", "external/operational-saas"],
    anatomy: [
      { name: "sourceList", purpose: "Visible source documents, links, or citations." },
      { name: "reviewState", purpose: "Human or system review state in text." },
      { name: "uncertainty", purpose: "Limitation or missing-evidence copy." },
      { name: "checkedAt", purpose: "Last source check time." },
      { name: "reviewer", purpose: "Named reviewer or role responsible for the evidence state." },
      { name: "safeAction", purpose: "Attach, inspect, review, or export action." },
    ],
    requiredFields: ["sourceList", "checkedAt", "reviewState", "uncertainty", "reviewer", "safeAction"],
    variants: [
      { name: "rail", purpose: "Evidence alongside selected work." },
      { name: "embedded", purpose: "Evidence inside a decision surface." },
    ],
    accessibilityHooks: accessibilityHooks("Use a labelled evidence region with a semantic source list and visible review status.", "Read sources, checked time, review state and reviewer, uncertainty, then the safe action."),
    states: [
      { name: "available", purpose: "The source is available for review.", requiredVisibleSignals: ["available", "source", "captured time"] },
      { name: "requested", purpose: "Evidence has been requested but is not available.", requiredVisibleSignals: ["requested", "request owner", "next check"] },
      { name: "missing", purpose: "Required evidence is missing.", requiredVisibleSignals: ["missing", "impact", "safe action"] },
      { name: "stale", purpose: "Evidence needs a new source check.", requiredVisibleSignals: ["stale", "last reviewed", "refresh owner"] },
      { name: "disputed", purpose: "Evidence interpretation is disputed.", requiredVisibleSignals: ["disputed", "reviewer", "limitation"] },
      { name: "under-review", purpose: "A named reviewer is assessing the evidence.", requiredVisibleSignals: ["under review", "reviewer", "source count"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: responsive,
    exemplarRoutes: ["/patterns/axal/", "/lab/axal-review-desk/"],
    adopterGuidance: guidance,
    nonGoals: ["AI authority", "source ingestion", "legal advice"],
  }),
  defineProductPattern({
    name: "HumanReviewCheckpoint",
    group: "axal-workspace",
    purpose: "Block consequential progression until a named human opens the evidence and records a decision.",
    ...workspaceRules,
    userJob: "Open the required evidence and record or defer a consequential human decision safely.",
    semanticRoot: "A labelled section that places decision context and evidence before decision actions.",
    intendedProducts: ["axal/workspace", "complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "checkpointLabel", purpose: "Human decision requirement." },
      { name: "preparationState", purpose: "Current draft or preparation state." },
      { name: "reviewOwner", purpose: "Named role or person." },
      { name: "sourceReadiness", purpose: "Whether required sources can support a decision." },
      { name: "blockers", purpose: "Named reasons the decision must be held." },
      { name: "decisionQuestion", purpose: "Specific decision to make." },
      { name: "evidenceLink", purpose: "Source to inspect before deciding." },
      { name: "decisionActions", purpose: "Approve, revise, request evidence, or defer." },
      { name: "nextSafeAction", purpose: "Consumer-owned action that can safely advance the review." },
      { name: "timestampHistory", purpose: "Recorded time or history reference when present." },
    ],
    requiredFields: ["preparationState", "reviewOwner", "sourceReadiness", "blockers", "decisionActions", "nextSafeAction", "timestampHistory"],
    variants: [
      { name: "inverse", purpose: "High-emphasis checkpoint inside a review desk." },
      { name: "inline", purpose: "Checkpoint attached to a work record." },
    ],
    accessibilityHooks: accessibilityHooks("Use a labelled checkpoint section; native buttons expose the decision verb and never imply authorization from styling.", "Read preparation, owner, source readiness and blockers before evidence, decision actions, next safe action, and history."),
    states: [
      { name: "preparation", purpose: "Draft preparation is still in progress.", requiredVisibleSignals: ["preparation", "draft", "next action"] },
      { name: "review-needed", purpose: "A named human decision is outstanding.", requiredVisibleSignals: ["review needed", "owner", "evidence"] },
      { name: "held", purpose: "The reviewer has paused the decision.", requiredVisibleSignals: ["held", "reason", "resume condition"] },
      { name: "approved", purpose: "A named reviewer recorded approval.", requiredVisibleSignals: ["approved", "reviewer", "recorded time"] },
      { name: "rejected-returned", purpose: "The item was rejected or returned for revision.", requiredVisibleSignals: ["returned", "reason", "next action"] },
      { name: "blocked", purpose: "The reviewer cannot decide safely.", requiredVisibleSignals: ["blocked", "reason", "request evidence"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: ["Keep evidence link before decision actions.", "Wrap actions without changing their primary and secondary hierarchy."],
    exemplarRoutes: ["/patterns/axal/", "/lab/axal-review-desk/"],
    adopterGuidance: guidance,
    nonGoals: ["automatic approval", "signature implementation", "authorization policy"],
  }),
  defineProductPattern({
    name: "AuditTrailPreview",
    group: "axal-workspace",
    purpose: "Show a bounded chronological trace of source, owner, and review events.",
    ...workspaceRules,
    userJob: "Understand the recent sequence of source, ownership, and review-state changes.",
    semanticRoot: "A labelled section containing an ordered list of timestamped events.",
    intendedProducts: ["axal/workspace", "external/operational-saas"],
    anatomy: [
      { name: "events", purpose: "Time, action, actor, and evidence reference." },
      { name: "resultingState", purpose: "State produced by each event." },
      { name: "optionalNote", purpose: "Bounded context that does not replace the source reference." },
      { name: "scope", purpose: "What the preview includes and omits." },
      { name: "inspectAction", purpose: "Route to the authoritative trail." },
    ],
    requiredFields: ["events", "resultingState"],
    variants: [
      { name: "rail", purpose: "Compact chronological evidence rail." },
      { name: "list", purpose: "Standalone audit event list." },
    ],
    accessibilityHooks: accessibilityHooks("Use an ordered list; each event keeps time, actor, action, source, and resulting state together.", "Traverse events chronologically, then reach the authoritative-trail action."),
    states: [
      { name: "compact", purpose: "A bounded chronological excerpt is available.", requiredVisibleSignals: ["time", "actor", "action"] },
      { name: "expanded", purpose: "Events expose source, resulting state, and note context.", requiredVisibleSignals: ["source", "resulting state", "chronological order"] },
      { name: "empty", purpose: "No events are recorded.", requiredVisibleSignals: ["no events", "scope", "last checked"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: ["Keep time, actor, and action in one semantic list item.", "Do not rely on a visual timeline line for event order."],
    exemplarRoutes: ["/patterns/axal/", "/lab/axal-review-desk/"],
    adopterGuidance: guidance,
    nonGoals: ["immutable audit storage", "complete system log", "security event monitoring"],
  }),
  defineProductPattern({
    name: "WorkQueueRow",
    group: "axal-workspace",
    purpose: "Make a review item scannable by identity, priority, source state, owner, due state, and review status.",
    ...workspaceRules,
    userJob: "Compare queued records and choose the next review item without losing source or ownership context.",
    semanticRoot: "A list item or article with one selection target and labelled work metadata.",
    intendedProducts: ["axal/workspace", "external/operational-saas"],
    anatomy: [
      { name: "identity", purpose: "Record ID and specific work title." },
      { name: "clientEntity", purpose: "Clearly synthetic client or entity label." },
      { name: "priority", purpose: "Text priority and ordering cue." },
      { name: "sourceState", purpose: "Linked, requested, or missing source state." },
      { name: "owner", purpose: "Named current owner." },
      { name: "dueState", purpose: "Date or relative due context." },
      { name: "reviewState", purpose: "Human review requirement." },
      { name: "blockedReason", purpose: "Why the work cannot advance, or an explicit no-blocker state." },
      { name: "nextSafeAction", purpose: "Review, evidence, or handoff action." },
    ],
    requiredFields: ["identity", "clientEntity", "dueState", "owner", "sourceState", "reviewState", "blockedReason", "nextSafeAction"],
    variants: [
      { name: "compact", purpose: "Dense queue list row." },
      { name: "card", purpose: "Narrow-screen grouped row." },
    ],
    accessibilityHooks: accessibilityHooks("Use a semantic list item or article; selected state and priority remain visible text and programmatically determinable.", "Read identity, entity, priority, source, owner, due and review state, blocker, then the next safe action."),
    states: [
      { name: "selected", purpose: "Row is the active work item.", requiredVisibleSignals: ["selected", "identity", "review state"] },
      { name: "waiting", purpose: "External evidence is pending.", requiredVisibleSignals: ["waiting", "dependency", "owner"] },
      { name: "ready", purpose: "Evidence is ready for review.", requiredVisibleSignals: ["ready", "source linked", "review owner"] },
      { name: "overdue", purpose: "Due time has passed.", requiredVisibleSignals: ["overdue", "due date", "owner"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: ["Move secondary metadata beneath the identity on narrow screens.", "Preserve row selection and status text in forced-colors mode."],
    exemplarRoutes: ["/patterns/axal/", "/lab/axal-review-desk/"],
    adopterGuidance: guidance,
    nonGoals: ["virtualized list", "queue persistence", "assignment mutation"],
  }),
] as const);
