import { defineProductPattern } from "../product-pattern-definition.ts";

const publicRules = {
  primaryProductMode: "complyeaze/core" as const,
  copyObligations: ["Name the product claim, its source or limitation, and the human-owned next action in visible text."],
  prohibitedClaims: ["government affiliation", "guaranteed outcome", "unsupported verified or approved status", "unsupported production readiness"],
  reducedMotionBehavior: ["Keep all claims, proof, boundaries, and actions visible without entrance or layout motion."],
  forcedColorsBehavior: ["Retain labelled boundaries, native link underlines, focus outlines, and status text without authored color."],
  syntheticRequirement: "Gallery and reference content must visibly identify synthetic prices, entities, dates, queues, and proof.",
  consumerResponsibilities: ["Supply current product copy, sources, destinations, prices, review ownership, and all runtime behavior."],
} as const;

function accessibilityHooks(semantics: string, focusOrder: string) {
  return {
    semantics,
    keyboard: "Use native links, buttons, and disclosures; every action remains reachable with a visible focus indicator.",
    announcements: "Announce only real status changes; static claims and proof do not create live regions.",
    focusOrder,
  } as const;
}

const responsive = [
  "Collapse split editorial compositions to a single reading column below the content breakpoint.",
  "Keep proof, boundary, and action copy adjacent; never move proof after unrelated promotion content.",
] as const;

const guidance = [
  "Use specific product, source, and operating-boundary language.",
  "Prefer one strong editorial composition over a grid of interchangeable cards.",
] as const;

const trust = [
  "Do not imply government affiliation, guaranteed outcomes, or unstated production readiness.",
  "Name account, upload, local-processing, external-destination, and human-review boundaries before action.",
] as const;

export const publicProductPatterns = Object.freeze([
  defineProductPattern({
    name: "PublicHero",
    group: "public-product",
    purpose: "Lead a public product page with a specific user decision, boundary, and evidence-backed action.",
    ...publicRules,
    userJob: "Understand the product outcome and trust boundary before choosing a route.",
    semanticRoot: "A labelled header containing one heading, one message region, actions, proof, and an optional boundary statement.",
    intendedProducts: ["complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "eyebrow", purpose: "Product or operating-boundary context." },
      { name: "title", purpose: "Decision-led public promise." },
      { name: "lede", purpose: "Scope, audience, and boundary explanation." },
      { name: "actions", purpose: "Primary and optional secondary action." },
      { name: "proof", purpose: "Short visible evidence or operating-mode note." },
      { name: "boundaryStatement", purpose: "Optional visible account, upload, custody, or review boundary." },
    ],
    requiredFields: ["title", "lede", "actions", "proof"],
    variants: [
      { name: "editorial", purpose: "Asymmetric advisory-publication layout." },
      { name: "compact", purpose: "Single-column route introduction." },
    ],
    accessibilityHooks: accessibilityHooks("Use a page or section header with one correctly ranked heading and native navigation actions.", "Read the claim, scope, proof or boundary, then the primary action."),
    states: [
      { name: "default", purpose: "The outcome, support, and primary action are available.", requiredVisibleSignals: ["outcome-first heading", "supporting paragraph", "primary action"] },
      { name: "with-proof-artifact", purpose: "A bounded proof object accompanies the public claim.", requiredVisibleSignals: ["proof object", "source or limitation", "boundary"] },
      { name: "compact-mobile", purpose: "The same claim and proof are sequenced for a narrow viewport.", requiredVisibleSignals: ["single heading", "proof after claim", "safe action"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: responsive,
    exemplarRoutes: ["/patterns/public/", "/lab/complyeaze-core/"],
    adopterGuidance: guidance,
    nonGoals: ["generic SaaS hero", "unsupported trust headline", "three-equal-card pitch"],
  }),
  defineProductPattern({
    name: "ProductRouteMap",
    group: "public-product",
    purpose: "Compare workspace, local utility, and browser-local routes without flattening their boundaries.",
    ...publicRules,
    userJob: "Choose the correct product route by persistence, custody, account, upload, and review needs.",
    semanticRoot: "A labelled section containing one primary route, bounded alternatives, and a separate design-evidence colophon.",
    intendedProducts: ["complyeaze/core", "axal/workspace", "pack/local-utility", "tools/local-artifact"],
    anatomy: [
      { name: "routeSummary", purpose: "Why the user is choosing a route." },
      { name: "primaryRoute", purpose: "Highest-context route with live proof preview." },
      { name: "secondaryRoutes", purpose: "Alternative product modes." },
      { name: "boundaryLabels", purpose: "Account, custody, upload, and review distinctions." },
      { name: "routeActions", purpose: "Named destinations for each route." },
      { name: "currentStatus", purpose: "Availability or limitation for each route where applicable." },
      { name: "proofOrSource", purpose: "Optional evidence attached to a route claim." },
      { name: "colophon", purpose: "Sanchika evidence path without forcing it into the product list." },
    ],
    requiredFields: ["routeSummary", "primaryRoute", "secondaryRoutes", "boundaryLabels", "routeActions", "colophon"],
    variants: [{ name: "family", purpose: "One primary route plus bounded alternatives." }],
    states: [
      { name: "default", purpose: "All documented routes are available.", requiredVisibleSignals: ["product names", "operating modes", "boundary labels"] },
      { name: "compact", purpose: "Routes retain priority and boundaries in a narrow composition.", requiredVisibleSignals: ["primary route", "bounded alternatives", "next actions"] },
      { name: "limited", purpose: "A route is available with a named limitation.", requiredVisibleSignals: ["limited", "scope", "fallback"] },
      { name: "unavailable", purpose: "A route needs a reason and fallback.", requiredVisibleSignals: ["unavailable", "reason", "fallback"] },
      { name: "colophon", purpose: "The design-system evidence path is shown outside the peer product routes.", requiredVisibleSignals: ["Sanchika", "evidence link", "not a product route"] },
    ],
    accessibilityHooks: accessibilityHooks("Use a section with route headings and native links; keep the Sanchika colophon outside the peer-route list.", "Read the route purpose and boundary before its action; read the colophon after all product routes."),
    trustBoundaries: trust,
    responsiveBehavior: ["Stack routes in priority order on narrow screens.", "Keep each boundary label with its route action."],
    exemplarRoutes: ["/patterns/public/", "/lab/complyeaze-core/"],
    adopterGuidance: guidance,
    nonGoals: ["application router", "authentication", "pricing matrix"],
  }),
  defineProductPattern({
    name: "ProofStrip",
    group: "public-product",
    purpose: "Summarize bounded proof signals without turning them into decorative metrics.",
    ...publicRules,
    userJob: "Inspect the source, freshness, and limitation behind a compact set of product facts.",
    semanticRoot: "A labelled description list whose every proof item includes a source link and limitation or status.",
    intendedProducts: ["complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "proofItems", purpose: "Label, value, source, and limitation for each signal." },
      { name: "checkedAt", purpose: "Evidence freshness or artifact state." },
    ],
    requiredFields: ["proofItems", "checkedAt"],
    variants: [{ name: "inline", purpose: "Compact horizontal proof ledger." }],
    states: [
      { name: "verified", purpose: "Proof is linked and current.", requiredVisibleSignals: ["verified", "source", "checked time"] },
      { name: "limited", purpose: "Evidence is incomplete.", requiredVisibleSignals: ["limited", "missing proof", "next check"] },
    ],
    accessibilityHooks: accessibilityHooks("Use a description list or semantic list; each fact keeps its label, value, source, and limitation together.", "Visit proof items in reading order and expose each source immediately after its fact."),
    trustBoundaries: trust,
    responsiveBehavior: ["Wrap proof items into a semantic list.", "Never truncate source or limitation copy."],
    exemplarRoutes: ["/patterns/public/", "/lab/complyeaze-core/"],
    adopterGuidance: guidance,
    nonGoals: ["vanity metrics", "animated counters", "evidence-free badges"],
  }),
  defineProductPattern({
    name: "TrustBoundary",
    group: "public-product",
    purpose: "Explain what data stays local, leaves the device, requires an account, or needs human judgment.",
    ...publicRules,
    userJob: "Know what crosses a named boundary, what never crosses, and who controls the next action.",
    semanticRoot: "A labelled aside or section that states the boundary before the related action.",
    intendedProducts: ["complyeaze/core", "axal/workspace", "pack/local-utility", "tools/local-artifact", "external/operational-saas"],
    anatomy: [
      { name: "boundarySummary", purpose: "One-line boundary statement." },
      { name: "boundaryFacts", purpose: "Account, upload, network, permission, and review facts." },
      { name: "neverCrosses", purpose: "Sensitive data or credentials that do not cross the named boundary." },
      { name: "actionOwner", purpose: "Person or system that controls a boundary-crossing action." },
      { name: "sourceEvidence", purpose: "Inspectable source for the boundary statement." },
      { name: "safeAction", purpose: "Inspect, permission, fallback, or handoff action." },
    ],
    requiredFields: ["boundarySummary", "boundaryFacts", "neverCrosses", "actionOwner", "sourceEvidence", "safeAction"],
    variants: [
      { name: "workspace", purpose: "Saved-context and human-review boundary." },
      { name: "local", purpose: "Device custody and portal-session boundary." },
      { name: "draft", purpose: "Browser-local draft boundary." },
      { name: "inverse", purpose: "High-contrast boundary on a dark artifact." },
    ],
    accessibilityHooks: accessibilityHooks("Use an aside or labelled section with text facts; never encode the boundary as color or iconography alone.", "Read what crosses and never crosses, then the owner, source evidence, and safe action."),
    states: [
      { name: "local-only", purpose: "No artifact leaves the device.", requiredVisibleSignals: ["local", "no upload", "output destination"] },
      { name: "permission-required", purpose: "A capability must be granted.", requiredVisibleSignals: ["permission", "purpose", "fallback"] },
      { name: "upload-required", purpose: "An artifact must leave the device.", requiredVisibleSignals: ["destination", "reason", "processor"] },
      { name: "unavailable", purpose: "The boundary cannot be completed safely.", requiredVisibleSignals: ["unavailable", "reason", "manual path"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: ["Stack facts after the claim on narrow screens.", "Keep boundary summary before the related action in DOM order."],
    exemplarRoutes: ["/patterns/public/", "/patterns/pack/", "/lab/complyeaze-core/", "/lab/axal-review-desk/", "/lab/pack-local-proof/"],
    adopterGuidance: guidance,
    nonGoals: ["privacy-policy substitute", "security certification", "decorative reassurance"],
  }),
  defineProductPattern({
    name: "SourceProvenanceStrip",
    group: "public-product",
    purpose: "Attach source identity, checked time, reviewer, and uncertainty to a public claim.",
    ...publicRules,
    userJob: "Verify which source supports a claim, who checked it, when, and with what limitation.",
    semanticRoot: "A labelled description list with a visible source link, status, reviewer, checked time, and limitation.",
    intendedProducts: ["complyeaze/core", "pack/local-utility", "external/operational-saas"],
    anatomy: [
      { name: "claim", purpose: "Claim being supported." },
      { name: "sourceType", purpose: "Repository, document, release, or other source classification." },
      { name: "sources", purpose: "Linked primary or public sources." },
      { name: "releaseVersion", purpose: "Release, version, or explicit unreleased status." },
      { name: "checksumReference", purpose: "Checksum or reference when one exists." },
      { name: "checkedAt", purpose: "Last verification time." },
      { name: "reviewOwner", purpose: "Named person or method responsible for review." },
      { name: "visibleStatus", purpose: "Current evidence state in text." },
      { name: "limitation", purpose: "Uncertainty or missing evidence." },
    ],
    requiredFields: ["claim", "sources", "checkedAt", "reviewOwner", "visibleStatus", "limitation"],
    variants: [{ name: "ledger", purpose: "Compact source-and-review ledger." }],
    states: [
      { name: "current", purpose: "Sources and checks are current.", requiredVisibleSignals: ["source", "checked", "review owner"] },
      { name: "stale", purpose: "A source check needs refresh.", requiredVisibleSignals: ["stale", "last checked", "refresh owner"] },
      { name: "unavailable", purpose: "The source cannot be retrieved.", requiredVisibleSignals: ["unavailable", "last known reference", "safe action"] },
      { name: "limited", purpose: "The source supports only part of the claim.", requiredVisibleSignals: ["limited", "supported scope", "missing proof"] },
      { name: "unverified", purpose: "No completed source review supports the claim.", requiredVisibleSignals: ["unverified", "do not rely", "review owner"] },
    ],
    accessibilityHooks: accessibilityHooks("Use a description list with native source links and visible status text.", "Read the claim, source, checked time, reviewer, status, then limitation."),
    trustBoundaries: trust,
    responsiveBehavior: ["Wrap metadata without separating it from the claim.", "Allow source links to break safely without horizontal scroll."],
    exemplarRoutes: ["/patterns/public/", "/patterns/pack/", "/lab/pack-local-proof/"],
    adopterGuidance: guidance,
    nonGoals: ["citation generator", "statutory authority", "hidden source drawer"],
  }),
  defineProductPattern({
    name: "PricingBlock",
    group: "public-product",
    purpose: "Describe price, inclusions, exclusions, and human-review limits without urgency or guarantee language.",
    ...publicRules,
    userJob: "Understand one current price and its inclusions, exclusions, effective date, and review boundary.",
    semanticRoot: "A labelled section containing exactly one authoritative price and its source owner.",
    intendedProducts: ["complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "offerName", purpose: "Specific service or package." },
      { name: "price", purpose: "Currency, cadence, and tax qualification." },
      { name: "status", purpose: "Introductory, current, planned, or synthetic exemplar status." },
      { name: "effectiveAt", purpose: "Effective or last-reviewed date." },
      { name: "inclusions", purpose: "What is included." },
      { name: "exclusions", purpose: "What remains outside scope." },
      { name: "reviewBoundary", purpose: "Human or professional review responsibility." },
      { name: "action", purpose: "Consult or purchase action." },
      { name: "sourceOwner", purpose: "Consumer-owned authoritative pricing source." },
    ],
    requiredFields: ["price", "status", "effectiveAt", "inclusions", "exclusions", "reviewBoundary", "action", "sourceOwner"],
    variants: [{ name: "single-offer", purpose: "One clearly bounded offer." }],
    states: [{ name: "available", purpose: "Price and scope are current.", requiredVisibleSignals: ["price", "cadence", "inclusions", "exclusions"] }],
    accessibilityHooks: accessibilityHooks("Use a labelled section; express price, cadence, tax qualification, inclusions, and exclusions as text.", "Read price status and effective date before inclusions, exclusions, review boundary, and action."),
    trustBoundaries: trust,
    responsiveBehavior: responsive,
    exemplarRoutes: ["/patterns/public/"],
    adopterGuidance: guidance,
    nonGoals: ["dark-pattern urgency", "guaranteed outcome", "comparison-card wall"],
  }),
  defineProductPattern({
    name: "FAQAccordion",
    group: "public-product",
    purpose: "Answer high-trust product questions with native disclosure semantics and visible scope limits.",
    ...publicRules,
    userJob: "Expand a specific trust or scope question and inspect its answer and source.",
    semanticRoot: "A labelled section containing native details and summary pairs.",
    intendedProducts: ["complyeaze/core", "external/operational-saas"],
    anatomy: [
      { name: "question", purpose: "Specific user question." },
      { name: "answer", purpose: "Plain-language answer with boundary." },
      { name: "source", purpose: "Optional supporting public source." },
    ],
    requiredFields: ["question", "answer"],
    variants: [{ name: "stack", purpose: "Single-column native details list." }],
    states: [
      { name: "collapsed", purpose: "Question remains visible.", requiredVisibleSignals: ["question", "disclosure state"] },
      { name: "expanded", purpose: "Answer and source are visible.", requiredVisibleSignals: ["question", "answer", "boundary"] },
    ],
    accessibilityHooks: {
      semantics: "Use native details and summary for every question and answer pair.",
      keyboard: "Preserve native summary keyboard activation and a visible focus indicator.",
      announcements: "Native details and summary expose name, role, and expanded state without a custom live region.",
      focusOrder: "Visit each question in document order; its answer and source follow immediately when expanded.",
    },
    trustBoundaries: trust,
    responsiveBehavior: ["Keep disclosure targets at least the control-height minimum.", "Do not split a question from its answer."],
    exemplarRoutes: ["/patterns/public/"],
    adopterGuidance: guidance,
    nonGoals: ["SEO copy dump", "exclusive accordion behavior", "hidden limitation text"],
  }),
  defineProductPattern({
    name: "ReleaseStatusBanner",
    group: "public-product",
    purpose: "State release, preview, limitation, or maintenance status with a dated evidence link.",
    ...publicRules,
    userJob: "Determine whether a named release artifact supports the intended use and what limitation remains.",
    semanticRoot: "A labelled aside with snapshot status, version or artifact, date, source link, limitation, and safe action.",
    intendedProducts: ["complyeaze/core", "pack/local-utility", "tools/local-artifact", "external/operational-saas"],
    anatomy: [
      { name: "status", purpose: "Visible release state." },
      { name: "productPackage", purpose: "Product or package whose status is being shown." },
      { name: "releaseVersion", purpose: "Current release, version, artifact, or explicit unreleased status." },
      { name: "scope", purpose: "Affected product or artifact." },
      { name: "effectiveAt", purpose: "Status date or maintenance window." },
      { name: "source", purpose: "Inspectable release or source artifact." },
      { name: "supportedScope", purpose: "What the release evidence supports." },
      { name: "knownLimitation", purpose: "What remains unavailable or unproven." },
      { name: "safeAction", purpose: "Review, update, or fallback action." },
    ],
    requiredFields: ["productPackage", "releaseVersion", "effectiveAt", "status", "source", "supportedScope", "knownLimitation", "safeAction"],
    variants: [
      { name: "notice", purpose: "Neutral release information." },
      { name: "warning", purpose: "Limited or maintenance state." },
    ],
    accessibilityHooks: accessibilityHooks("Use a labelled aside with visible release status and a native evidence link.", "Read status, artifact and date, supported scope, limitation, then the safe action."),
    states: [
      { name: "current", purpose: "Release evidence is current.", requiredVisibleSignals: ["current", "version or artifact", "evidence"] },
      { name: "alpha", purpose: "The release is explicitly pre-stable.", requiredVisibleSignals: ["alpha", "supported scope", "limitation"] },
      { name: "stale", purpose: "The release evidence needs a new source check.", requiredVisibleSignals: ["stale", "last reviewed", "refresh action"] },
      { name: "limited", purpose: "A release limitation affects use.", requiredVisibleSignals: ["limited", "scope", "fallback"] },
      { name: "planned", purpose: "The release is planned but not available.", requiredVisibleSignals: ["planned", "no release claim", "source"] },
      { name: "unavailable", purpose: "No supported release artifact is available.", requiredVisibleSignals: ["unavailable", "reason", "safe action"] },
    ],
    trustBoundaries: trust,
    responsiveBehavior: ["Stack status metadata before actions on narrow screens.", "Keep date and evidence link untruncated."],
    exemplarRoutes: ["/patterns/public/", "/patterns/pack/", "/lab/pack-local-proof/"],
    adopterGuidance: guidance,
    nonGoals: ["release automation", "version source of truth", "dismiss-only incident notice"],
  }),
] as const);
