import type { PrimitiveContract } from "./types.js";

export const actionPrimitiveSpecs = [
  {
    name: "Button",
    role: "Command trigger",
    purpose: "Triggers an action without implying navigation and preserves the v0.0.2 tone, size, class, and visible-state contract.",
    whenToUse: ["Submitting", "Opening or changing UI state", "Explicit user commands"],
    whenNotToUse: ["For navigation", "For an anchor styled as a command", "For disabled actions without a visible reason"],
    semanticElement: "Prefer native button with an explicit type. Non-button role=button implementations remain a consumer exception with full APG obligations.",
    classHooks: [".sk-button", ".sk-tone-brand", ".sk-tone-neutral", ".sk-tone-danger", ".sk-size-sm", ".sk-size-md", ".sk-size-lg"],
    anatomy: [{ name: "label", purpose: "Stable accessible command name." }, { name: "optional icon", purpose: "Supporting icon that does not replace the label." }, { name: "loading indicator", purpose: "Visual pending indicator that does not change intrinsic button size." }],
    variants: [{ name: "tone", values: ["brand", "neutral", "danger"], defaultValue: "neutral" }, { name: "size", values: ["sm", "md", "lg"], defaultValue: "md" }],
    tones: ["brand", "neutral", "danger"], sizes: ["sm", "md", "lg"],
    requiredStates: ["default", "hover", "focus-visible", "pressed", "disabled", "loading"],
    stateEvidence: [
      { state: "default", attributes: ["type"], selectors: [".sk-button"], notes: "Default buttons must expose an accessible text label." },
      { state: "hover", attributes: [], selectors: [".sk-button:hover"], notes: "Hover treatment must not be the only state cue." },
      { state: "focus-visible", attributes: [], selectors: [".sk-button:focus-visible"], notes: "Keyboard focus must be visibly distinct from hover." },
      { state: "pressed", attributes: ["aria-pressed"], selectors: [".sk-button[aria-pressed=\"true\"]"], notes: "Toggle buttons must expose aria-pressed while keeping a stable visible label." },
      { state: "disabled", attributes: ["disabled", "aria-disabled", "data-disabled"], selectors: [".sk-button:disabled", ".sk-button[aria-disabled=\"true\"]", ".sk-button[data-disabled=\"true\"]"], notes: "Prefer native disabled. If aria-disabled or data-disabled is used, consumers must suppress click, Space, Enter, and shortcut activation while keeping a visible disabled reason." },
      { state: "loading", attributes: ["aria-busy", "data-loading"], selectors: [".sk-button[aria-busy=\"true\"]", ".sk-button[data-loading=\"true\"]"], notes: "Loading state must expose aria-busy as the semantic loading state. data-loading is a visual hook only and is not assistive-technology evidence by itself." },
    ],
    standards: [{ id: "WAI-ARIA APG Button Pattern", sourceUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/button/", requirements: ["Prefer native <button> elements for command actions.", "If a non-button element uses role=\"button\", the consumer must provide Space and Enter activation.", "Toggle buttons use aria-pressed without changing the visible label.", "Consumers must define focus after activation according to the resulting workflow."] }],
    keyboardObligations: ["Native button activation", "Space and Enter for role=button exceptions", "Suppress all activation paths when aria-disabled", "Keep focus predictable after activation"],
    screenReaderObligations: ["Provide an accessible name", "Expose aria-pressed for toggles", "Expose aria-busy for loading", "Associate disabled reason when needed"],
    contentRules: ["Use an action verb", "Keep loading label stable", "Do not style navigation anchors as Button", "Use lg for primary mobile actions when a practical touch target is required"],
    motion: { behavior: "Only token-driven color and focus feedback; the loading indicator stays static with no lift, bounce, or critical-action choreography.", reducedMotion: "Transitions are removed while the static loading indicator and visible pending text/state remain." },
    forcedColorsBehavior: ["Focus uses system Highlight", "Control boundary uses ButtonText", "Disabled and pressed state remain visible without authored color"],
    mobileBehavior: ["Labels wrap", "The control stays within available width", "Primary mobile actions should use the large size or consumer-owned full-width composition"],
    examples: [{ title: "Primary command", className: "sk-button sk-tone-brand sk-size-lg", markup: "<button class=\"sk-button sk-tone-brand sk-size-lg\" type=\"button\">Start review</button>" }],
    galleryCoverage: ["All six states", "All compatible tones and sizes", "Forced colors", "No loading layout shift"],
    consumerResponsibilities: ["Implement runtime action and loading logic", "Manage focus after workflows", "Suppress activation for aria-disabled", "Provide visible disabled reasons"],
    accessibility: ["keyboard-operable", "visible-focus", "non-color-disabled-state"],
  },
  {
    name: "Link",
    role: "Navigation target",
    purpose: "Navigates to another document, route, fragment, or downloadable resource with a persistent non-color affordance.",
    whenToUse: ["Navigation", "Source and policy destinations", "Downloads when href identifies the resource"],
    whenNotToUse: ["For commands", "For toggle behavior", "When an external destination is unnamed"],
    semanticElement: "Use a native anchor with href. Link does not turn non-anchor elements into navigation controls.",
    classHooks: [".sk-link", ".sk-link-default", ".sk-link-quiet"],
    anatomy: [{ name: "label", purpose: "Destination or purpose understandable outside visual position." }, { name: "optional context", purpose: "External, download, or file-type naming in visible or assistive text." }],
    variants: [{ name: "variant", values: ["default", "quiet"], defaultValue: "default" }],
    tones: [], sizes: [], requiredStates: ["default", "hover", "focus-visible", "visited"],
    stateEvidence: [
      { state: "default", attributes: ["href"], selectors: [".sk-link"], notes: "Inline links keep an underline as a persistent non-color affordance." },
      { state: "hover", attributes: [], selectors: [".sk-link:hover"], notes: "Hover changes color while the underline remains." },
      { state: "focus-visible", attributes: [], selectors: [".sk-link:focus-visible"], notes: "Keyboard focus uses a visible outline and offset." },
      { state: "visited", attributes: [], selectors: [".sk-link:visited"], notes: "Visited treatment is deliberate and retains the same high-contrast link role in v0." },
    ],
    keyboardObligations: ["Native anchor activation and focus behavior", "Do not add button keyboard handlers"],
    screenReaderObligations: ["Name external destinations or include assistive context", "Avoid repeated ambiguous labels such as Read more"],
    contentRules: ["Use destination-led copy", "Name external links where context is not obvious", "Keep inline underline or another persistent non-color affordance"],
    motion: { behavior: "Only token-driven color feedback; no translation or lift.", reducedMotion: "Color feedback remains immediate when transitions are reduced." },
    forcedColorsBehavior: ["Underline remains", "Focus uses Highlight", "Link uses system LinkText where available"],
    mobileBehavior: ["Long labels wrap", "Inline links remain distinguishable at zoom"],
    examples: [{ title: "Source link", className: "sk-link sk-link-default", markup: "<a class=\"sk-link sk-link-default\" href=\"/source/\">Inspect source</a>" }],
    galleryCoverage: ["Default and quiet variants", "Visited state", "External naming", "Link versus Button"],
    consumerResponsibilities: ["Provide href", "Name external/download behavior", "Use Button for actions"],
    accessibility: ["persistent-link-affordance", "visible-focus", "native-anchor"],
  },
  {
    name: "LinkCard",
    role: "Single navigation target with grouped context",
    purpose: "Makes a bounded content group one accessible navigation target without nested interactive controls.",
    whenToUse: ["Directory entries", "Source or evidence destinations", "One destination with supporting metadata"],
    whenNotToUse: ["When the group needs multiple actions", "Around buttons, links, checkboxes, menus, or controls", "When a plain inline link is clearer"],
    semanticElement: "Prefer a root anchor containing non-interactive content. A single named-link pattern is allowed only when the consumer keeps the rest of the card non-interactive.",
    classHooks: [".sk-link-card", ".sk-link-card-default", ".sk-link-card-muted"],
    anatomy: [{ name: "root link", purpose: "The single navigation target." }, { name: "title", purpose: "Purpose understandable outside layout position." }, { name: "metadata", purpose: "Optional source, boundary, category, or state facts." }],
    variants: [{ name: "variant", values: ["default", "muted"], defaultValue: "default" }],
    tones: [], sizes: [], requiredStates: ["default", "hover", "focus-visible"],
    stateEvidence: [
      { state: "default", attributes: ["href"], selectors: [".sk-link-card"], notes: "The root anchor is the only interactive target and has a visible boundary." },
      { state: "hover", attributes: [], selectors: [".sk-link-card:hover"], notes: "Hover is supporting feedback; the boundary and title affordance exist without hover." },
      { state: "focus-visible", attributes: [], selectors: [".sk-link-card:focus-visible"], notes: "Focus treatment spans the card boundary." },
    ],
    keyboardObligations: ["Use native anchor keyboard behavior", "Never nest another interactive element", "Keep one tab stop"],
    screenReaderObligations: ["The link name must convey title and purpose", "Metadata must remain in sensible reading order"],
    contentRules: ["Exactly one navigation target", "No nested buttons, links, checkboxes, menus, fields, or controls", "Keep title and destination clear", "Boundary/source metadata is optional but must be truthful"],
    motion: { behavior: "Only border, background, and link-color feedback; no decorative lift.", reducedMotion: "State feedback remains immediate when transitions are reduced." },
    forcedColorsBehavior: ["A CanvasText boundary and Highlight focus remain visible."],
    mobileBehavior: ["Content wraps", "The single target spans the available inline size", "No horizontal overflow"],
    examples: [{ title: "Root-anchor card", className: "sk-link-card sk-link-card-default", markup: "<a class=\"sk-link-card sk-link-card-default\" href=\"/source/record/\"><strong>Source record</strong><span>Reviewed 13-07-2026</span></a>" }],
    galleryCoverage: ["Root-anchor example", "Named-link guidance", "Nested-interactive anti-example", "Forced-colors focus"],
    consumerResponsibilities: ["Enforce one interactive target", "Choose an understandable accessible name", "Keep application actions outside the LinkCard"],
    accessibility: ["single-tab-stop", "no-nested-interactive", "whole-boundary-focus"],
  },
  {
    name: "Card",
    role: "Grouped information surface",
    purpose: "Preserves the v0.0.2 Card API as a specialized grouped-content plane built on Surface styling rather than the default wrapper for every section.",
    whenToUse: ["A real grouped record", "Compatibility with existing sk-card consumers", "A content group that benefits from Card padding and quiet elevation"],
    whenNotToUse: ["For every section", "For visual planes without content-group meaning", "For nested Card-on-Card without real hierarchy"],
    semanticElement: "Use article, section, li, a, or another element matching the grouped content. Static cards are not focus targets.",
    classHooks: [".sk-card", ".sk-tone-neutral", ".sk-tone-info", ".sk-tone-success", ".sk-tone-warning", ".sk-tone-danger", ".sk-size-md", ".sk-size-lg"],
    anatomy: [{ name: "root", purpose: "The grouped content element." }, { name: "heading", purpose: "Visible label for the content group." }, { name: "content", purpose: "Related record content." }],
    variants: [{ name: "tone", values: ["neutral", "info", "success", "warning", "danger"], defaultValue: "neutral" }, { name: "size", values: ["md", "lg"], defaultValue: "md" }],
    tones: ["neutral", "info", "success", "warning", "danger"], sizes: ["md", "lg"], requiredStates: ["default", "focus-visible"],
    stateEvidence: [
      { state: "default", attributes: [], selectors: [".sk-card"], notes: "Cards need semantic headings and visible status text when tone implies state." },
      { state: "focus-visible", attributes: ["href"], selectors: [".sk-card:focus-visible"], notes: "Interactive cards must use native link or button semantics and show a visible keyboard focus outline." },
    ],
    standards: [],
    keyboardObligations: ["Static Card is not focusable", "Interactive Card uses native link or button semantics"],
    screenReaderObligations: ["Use a semantic heading where the group needs a label", "Visible status text accompanies status tone"],
    contentRules: ["Surface is the visual plane; Card is grouped content", "Do not require new markup for v0.0.2 consumers", "Avoid nested Card-on-Card"],
    motion: { behavior: "Card adds no decorative motion.", reducedMotion: "No override is required." },
    forcedColorsBehavior: ["A CanvasText boundary remains visible", "Interactive focus uses Highlight"],
    mobileBehavior: ["Content and long identifiers wrap", "Card remains within available inline size"],
    examples: [{ title: "Compatible content card", className: "sk-card sk-tone-neutral sk-size-md", markup: "<article class=\"sk-card sk-tone-neutral sk-size-md\"><h3>Review record</h3><p>…</p></article>" }],
    galleryCoverage: ["Existing default and focus examples", "Card versus Surface", "Discouraged nested Card guidance"],
    consumerResponsibilities: ["Choose semantic grouping markup", "Keep static cards out of tab order", "Use LinkCard for a single navigation target"],
    accessibility: ["semantic-heading", "non-color-status-text"],
  },
] as const satisfies readonly PrimitiveContract[];
