import type { PrimitiveContract } from "./types.js";

export const formStatusPrimitiveSpecs = [
  {
    name: "Badge",
    role: "Short status or classification label",
    purpose: "Names a compact status or classification with visible text and supporting tone while preserving the v0.0.2 API.",
    whenToUse: ["Short state labels", "Compact classification"],
    whenNotToUse: ["As decorative pill clouds", "For long explanations", "As color-only status"],
    semanticElement: "Use span or another phrasing element; Badge adds no live-region behavior.",
    classHooks: [".sk-badge", ".sk-tone-neutral", ".sk-tone-success", ".sk-tone-warning", ".sk-tone-danger", ".sk-tone-info", ".sk-size-sm", ".sk-size-md"],
    anatomy: [{ name: "label", purpose: "Visible status or classification text." }],
    variants: [{ name: "tone", values: ["neutral", "success", "warning", "danger", "info"], defaultValue: "neutral" }, { name: "size", values: ["sm", "md"], defaultValue: "md" }],
    tones: ["neutral", "success", "warning", "danger", "info"], sizes: ["sm", "md"], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-badge"], notes: "Badge text must name the status; tone color is supporting evidence only." }],
    standards: [],
    keyboardObligations: ["Badge adds no keyboard behavior."],
    screenReaderObligations: ["Status meaning must be present in text", "Consumers add live-region semantics only when a real state update requires them"],
    contentRules: ["Keep labels short", "Do not imply official approval", "Do not use color alone"],
    motion: { behavior: "Badge adds no motion.", reducedMotion: "No override is needed." },
    forcedColorsBehavior: ["Text and boundary remain visible with system colors."],
    mobileBehavior: ["Long labels wrap instead of overflowing."],
    examples: [{ title: "Visible review status", className: "sk-badge sk-tone-warning sk-size-sm", markup: "<span class=\"sk-badge sk-tone-warning sk-size-sm\">CA review needed</span>" }],
    galleryCoverage: ["All compatible tones"],
    consumerResponsibilities: ["Supply visible status text", "Announce dynamic updates when required"],
    accessibility: ["visible-text-required", "color-not-only-signal"],
  },
  {
    name: "Field",
    role: "Accessible label, control, hint, and error wrapper",
    purpose: "Groups visible form guidance and preserves the v0.0.2 class/state contract without implementing validation or input behavior.",
    whenToUse: ["Labelled inputs", "Controls with hint or error text"],
    whenNotToUse: ["Without a visible label", "As a validation runtime", "For non-form layout"],
    semanticElement: "Use a neutral wrapper or fieldset where grouping semantics apply; labels and controls remain native elements.",
    classHooks: [".sk-field", "[data-sk-label]", "[data-sk-control]", "[data-sk-hint]", "[data-sk-error]"],
    anatomy: [{ name: "label", purpose: "Visible label associated to the control." }, { name: "control", purpose: "Native input, textarea, or select." }, { name: "hint", purpose: "Optional instructions." }, { name: "error", purpose: "Visible associated error copy." }],
    variants: [{ name: "tone", values: ["neutral", "danger"], defaultValue: "neutral" }, { name: "size", values: ["sm", "md", "lg"], defaultValue: "md" }],
    tones: ["neutral", "danger"], sizes: ["sm", "md", "lg"], requiredStates: ["default", "focus-visible", "disabled", "error"],
    stateEvidence: [
      { state: "default", attributes: ["for", "id", "name"], selectors: [".sk-field"], notes: "Fields must connect visible labels to controls." },
      { state: "focus-visible", attributes: [], selectors: [".sk-field :is(input, textarea, select, [data-sk-control]):focus-visible"], notes: "Control focus must be visible for keyboard users." },
      { state: "disabled", attributes: ["disabled", "data-disabled"], selectors: [".sk-field :is(input, textarea, select, [data-sk-control]):disabled", ".sk-field[data-disabled=\"true\"]"], notes: "Disabled field state must remain legible and discoverable." },
      { state: "error", attributes: ["aria-invalid", "aria-describedby", "data-sk-error"], selectors: [".sk-field[data-invalid=\"true\"]", ".sk-field :is(input, textarea, select, [data-sk-control])[aria-invalid=\"true\"]", "[data-sk-error]"], notes: "Errors must be visible text associated with the control; aria-invalid and aria-describedby belong on the control." },
    ],
    standards: [],
    keyboardObligations: ["Keep native control keyboard behavior", "Do not trap focus"],
    screenReaderObligations: ["Associate label, hint, and error", "Expose aria-invalid on the control"],
    contentRules: ["Placeholder never replaces label", "Errors state the problem and recovery", "Hints remain concise"],
    motion: { behavior: "Field adds only token-driven focus and color feedback.", reducedMotion: "No layout or content motion is required." },
    forcedColorsBehavior: ["Control boundary and focus remain visible with system colors."],
    mobileBehavior: ["Controls fill available inline size", "Labels and error text wrap"],
    examples: [{ title: "Associated error", className: "sk-field sk-tone-danger sk-size-md", markup: "<div class=\"sk-field sk-tone-danger sk-size-md\" data-invalid=\"true\"><label for=\"period\">Period</label><input id=\"period\" aria-invalid=\"true\" aria-describedby=\"period-error\"><p id=\"period-error\" data-sk-error>Source period is required.</p></div>" }],
    galleryCoverage: ["Default, focus, disabled, and error states"],
    consumerResponsibilities: ["Implement validation", "Associate visible labels and descriptions", "Keep native control semantics"],
    accessibility: ["label-required", "error-associated", "keyboard-operable"],
  },
] as const satisfies readonly PrimitiveContract[];
