import type { PrimitiveContract } from "./types.js";

const noMotion = {
  behavior: "The primitive defines no animation; consumer state changes remain immediate.",
  reducedMotion: "No override is needed because the primitive adds no motion.",
} as const;

export const layoutPlanePrimitiveSpecs = [
  {
    name: "Split",
    role: "Asymmetrical primary and supporting composition",
    purpose: "Pairs a primary region with supporting context using evidence-backed ratios and a deliberate narrow-screen stack.",
    whenToUse: ["Proof object plus explanation", "Primary work area plus supporting evidence", "Asymmetrical North Star structure"],
    whenNotToUse: ["When both regions are equal peers", "To visually reorder meaningful source content", "For page-specific hero geometry"],
    semanticElement: "Use a neutral wrapper with meaningful child regions; use section, article, or aside for slots only when their semantics are real.",
    classHooks: [".sk-split", ".sk-split-ratio-balanced", ".sk-split-ratio-primary", ".sk-split-ratio-supporting", ".sk-split-primary", ".sk-split-supporting", ".sk-split-gap-sm", ".sk-split-gap-md", ".sk-split-gap-lg"],
    anatomy: [{ name: "primary", purpose: "The dominant task or proof region." }, { name: "supporting", purpose: "Context, evidence, explanation, or secondary action." }],
    variants: [{ name: "ratio", values: ["balanced", "primary", "supporting"], defaultValue: "primary" }, { name: "gap", values: ["sm", "md", "lg"], defaultValue: "md" }],
    tones: [], sizes: [], requiredStates: ["default", "stacked"],
    stateEvidence: [
      { state: "default", attributes: [], selectors: [".sk-split"], notes: "Primary and supporting regions retain source order." },
      { state: "stacked", attributes: [], selectors: [".sk-split"], notes: "At narrow widths the regions resolve to one column without DOM reordering." },
    ],
    keyboardObligations: ["Split must not change tab order or use CSS ordering that contradicts the DOM."],
    screenReaderObligations: ["Primary content must precede supporting content when that is the meaningful reading order."],
    contentRules: ["Name primary and supporting responsibilities", "Keep one-off decorative geometry local", "Do not hide supporting content on mobile"],
    motion: noMotion,
    forcedColorsBehavior: ["Split adds no authored color or boundary."],
    mobileBehavior: ["Stacks to one column", "Retains logical source order", "Avoids horizontal overflow"],
    examples: [{ title: "Primary proof split", className: "sk-split sk-split-ratio-primary sk-split-gap-lg", markup: "<div class=\"sk-split sk-split-ratio-primary sk-split-gap-lg\"><div class=\"sk-split-primary\">…</div><aside class=\"sk-split-supporting\">…</aside></div>" }],
    galleryCoverage: ["Complete page skeleton", "Axal-like workbench shell", "Mobile stacked state"],
    consumerResponsibilities: ["Choose semantic child regions", "Keep source order logical", "Do not imply Split handles application behavior"],
    accessibility: ["source-order-preserved", "no-css-reordering", "narrow-stack"],
  },
  {
    name: "Surface",
    role: "Semantic visual plane",
    purpose: "Creates a restrained visual plane from S3 surface, border, radius, and elevation tokens while leaving content semantics to the chosen element.",
    whenToUse: ["Real visual planes", "Inset evidence regions", "Raised task surfaces", "Muted supporting context"],
    whenNotToUse: ["As the default wrapper for every section", "For decorative nesting", "To imply semantic grouping by appearance alone"],
    semanticElement: "Choose article, section, aside, div, fieldset, or another semantic element based on content; Surface adds no role.",
    classHooks: [".sk-surface", ".sk-surface-default", ".sk-surface-raised", ".sk-surface-inset", ".sk-surface-muted", ".sk-surface-inverse", ".sk-surface-pad-none", ".sk-surface-pad-sm", ".sk-surface-pad-md", ".sk-surface-pad-lg"],
    anatomy: [{ name: "root", purpose: "The semantic element that owns the visual plane." }, { name: "content", purpose: "Consumer-owned semantic content." }],
    variants: [{ name: "variant", values: ["default", "raised", "inset", "muted", "inverse"], defaultValue: "default" }, { name: "padding", values: ["none", "sm", "md", "lg"], defaultValue: "md" }],
    tones: [], sizes: [], requiredStates: ["default", "forced-colors"],
    stateEvidence: [
      { state: "default", attributes: ["data-surface"], selectors: [".sk-surface", ".sk-surface[data-surface=\"raised\"]"], notes: "Finite variants use classes or data-surface without changing content semantics." },
      { state: "forced-colors", attributes: [], selectors: [".sk-surface"], notes: "A system-color boundary remains visible when authored colors are replaced." },
    ],
    keyboardObligations: ["Static Surface is not focusable; interactive descendants own their keyboard behavior."],
    screenReaderObligations: ["Do not add a role solely because the plane is visually distinct."],
    contentRules: ["Prefer borders over shadows", "Avoid nested Surface-on-Surface unless hierarchy is real", "Do not use glow, glass, or status color without text"],
    motion: noMotion,
    forcedColorsBehavior: ["Uses a CanvasText boundary", "Inverse variants return to system Canvas and CanvasText"],
    mobileBehavior: ["Remains within the available inline size", "Padding stays finite and token-driven"],
    examples: [{ title: "Inset evidence surface", className: "sk-surface sk-surface-inset sk-surface-pad-md", markup: "<aside class=\"sk-surface sk-surface-inset sk-surface-pad-md\">…</aside>" }],
    galleryCoverage: ["Default, raised, inset, muted, and inverse planes", "Good and discouraged nesting guidance", "Forced-colors boundary"],
    consumerResponsibilities: ["Choose the semantic element", "Name visible state in content", "Avoid decorative nesting"],
    accessibility: ["forced-colors-boundary", "semantic-element-owned-by-consumer", "non-color-status"],
  },
  {
    name: "Divider",
    role: "Thematic or structural separator",
    purpose: "Marks a meaningful horizontal separation with border tokens and native semantics.",
    whenToUse: ["Thematic breaks", "Separating meaningful regions inside one composition"],
    whenNotToUse: ["Between every item", "As decorative noise", "For a vertical separator without a proven S4 need"],
    semanticElement: "Prefer hr for thematic separation; use role=\"separator\" only when that programmatic meaning is correct.",
    classHooks: [".sk-divider"],
    anatomy: [{ name: "root", purpose: "The native or explicitly semantic separator." }],
    variants: [], tones: [], sizes: [], requiredStates: ["default", "forced-colors"],
    stateEvidence: [
      { state: "default", attributes: ["role"], selectors: [".sk-divider"], notes: "Horizontal separation uses a token border and no decorative content." },
      { state: "forced-colors", attributes: [], selectors: [".sk-divider"], notes: "The separator uses system CanvasText." },
    ],
    keyboardObligations: ["Divider is never keyboard focusable."],
    screenReaderObligations: ["Use hr or role=separator only for meaningful separation."],
    contentRules: ["Do not add visible text inside the divider", "Do not repeat between every peer item"],
    motion: noMotion,
    forcedColorsBehavior: ["The boundary remains visible with CanvasText."],
    mobileBehavior: ["Spans the available inline size without overflow."],
    examples: [{ title: "Thematic divider", className: "sk-divider", markup: "<hr class=\"sk-divider\" />" }],
    galleryCoverage: ["Native thematic break", "Forced-colors boundary"],
    consumerResponsibilities: ["Decide whether the break is thematic", "Avoid decorative overuse"],
    accessibility: ["native-hr-preferred", "not-focusable", "forced-colors-visible"],
  },
  {
    name: "VisuallyHidden",
    role: "Assistive-technology-only text",
    purpose: "Keeps essential text available to assistive technology while removing it from the visual flow without a zoom clipping defect.",
    whenToUse: ["Clarifying an accessible name", "Adding context that is already visually unambiguous", "Skip-link text only when the link has a separate focus-reveal composition"],
    whenNotToUse: ["To hide content from screen readers", "To permanently hide a focusable control", "To replace visible labels or instructions"],
    semanticElement: "Use span or another text element; do not apply permanently to interactive controls.",
    classHooks: [".sk-visually-hidden"],
    anatomy: [{ name: "text", purpose: "Concise assistive text that remains in the accessibility tree." }],
    variants: [], tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-visually-hidden"], notes: "The content remains in the accessibility tree and does not use display:none or visibility:hidden." }],
    keyboardObligations: ["Do not apply to focusable controls", "A skip link must use a separate visible-on-focus composition."],
    screenReaderObligations: ["Text must add useful context", "Avoid duplicating nearby visible copy verbatim"],
    contentRules: ["Keep text concise", "Do not hide errors, labels, or status that sighted users also need"],
    motion: noMotion,
    forcedColorsBehavior: ["No authored color is required."],
    mobileBehavior: ["Remains available at zoom and on narrow screens."],
    examples: [{ title: "Accessible external-link context", className: "sk-visually-hidden", markup: "<span class=\"sk-visually-hidden\">Opens source repository</span>" }],
    galleryCoverage: ["Assistive-only label", "Focusable-control warning", "Skip-link guidance"],
    consumerResponsibilities: ["Verify the text is announced", "Keep focusable controls visible", "Test zoom and screen-reader behavior"],
    accessibility: ["assistive-technology-available", "zoom-safe", "not-display-none"],
  },
] as const satisfies readonly PrimitiveContract[];
