import type { PrimitiveContract } from "./types.js";

const noMotion = {
  behavior: "Layout changes are immediate; the primitive defines no animation or transition.",
  reducedMotion: "No override is needed because the primitive adds no motion.",
} as const;

export const layoutCorePrimitiveSpecs = [
  {
    name: "Container",
    role: "Bounded page or region measure",
    purpose: "Centers content, applies safe logical inline gutters, and selects an evidence-backed maximum measure without preventing full-bleed composition.",
    whenToUse: ["Page shells", "Reading regions", "Content and wide proof-object regions"],
    whenNotToUse: ["As component padding", "For negative-margin full bleed", "To invent page-specific maximum widths"],
    semanticElement: "Choose the region element that matches the content, commonly div, main, section, article, or nav.",
    classHooks: [".sk-container", ".sk-container-width-reading", ".sk-container-width-content", ".sk-container-width-wide", ".sk-container-width-full"],
    anatomy: [{ name: "root", purpose: "The semantic region whose inline measure is bounded." }],
    variants: [{ name: "width", values: ["reading", "content", "wide", "full"], defaultValue: "content" }],
    tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-container"], notes: "The root remains fluid below its selected maximum and uses logical inline padding." }],
    keyboardObligations: ["Container adds no keyboard behavior."],
    screenReaderObligations: ["Container adds no role; the consumer chooses the correct landmark or section semantics."],
    contentRules: ["Use one width mode", "Keep full bleed as a sibling composition", "Allow long identifiers to wrap inside descendants"],
    motion: noMotion,
    forcedColorsBehavior: ["Container adds no authored color or boundary."],
    mobileBehavior: ["Remains fluid", "Retains safe inline gutters", "Must not create horizontal overflow"],
    examples: [{ title: "Content container", className: "sk-container sk-container-width-content", markup: "<main class=\"sk-container sk-container-width-content\">…</main>" }],
    galleryCoverage: ["Reading copy", "Content layout", "Wide proof object"],
    consumerResponsibilities: ["Choose the semantic element", "Keep full-bleed content outside the bounded child instead of using negative margins"],
    accessibility: ["logical-inline-gutters", "zoom-safe", "no-horizontal-overflow"],
  },
  {
    name: "Section",
    role: "Vertical rhythm region",
    purpose: "Creates finite section-level block rhythm and an optional structural boundary without child-margin hacks.",
    whenToUse: ["Major content regions", "Narrative pauses", "Labelled sections with headings"],
    whenNotToUse: ["Inside dense controls", "For arbitrary padding", "As a replacement for Stack between siblings"],
    semanticElement: "Prefer section only when it has an accessible heading; otherwise use div, header, footer, or the appropriate landmark.",
    classHooks: [".sk-section", ".sk-section-space-sm", ".sk-section-space-md", ".sk-section-space-lg", ".sk-section-bordered"],
    anatomy: [{ name: "root", purpose: "The structural region." }, { name: "heading", purpose: "Optional heading that labels a semantic section." }],
    variants: [{ name: "space", values: ["sm", "md", "lg"], defaultValue: "md" }, { name: "boundary", values: ["none", "bordered"], defaultValue: "none" }],
    tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: ["aria-labelledby"], selectors: [".sk-section"], notes: "A semantic section should reference its visible heading when the relationship is not already native." }],
    keyboardObligations: ["Section adds no keyboard behavior."],
    screenReaderObligations: ["Do not create an unnamed section landmark", "Keep heading levels logical"],
    contentRules: ["Use one finite spacing mode", "Do not depend on first/last-child margin removal", "Use a boundary only when it separates real regions"],
    motion: noMotion,
    forcedColorsBehavior: ["The optional structural boundary remains visible with system CanvasText."],
    mobileBehavior: ["Token-driven block rhythm remains intentional without arbitrary mobile overrides."],
    examples: [{ title: "Labelled section", className: "sk-section sk-section-space-md sk-section-bordered", markup: "<section class=\"sk-section sk-section-space-md sk-section-bordered\" aria-labelledby=\"proof-title\">…</section>" }],
    galleryCoverage: ["Section with heading", "Section composed with Surface", "Mobile rhythm"],
    consumerResponsibilities: ["Choose the correct landmark or neutral element", "Provide a visible heading for semantic section elements"],
    accessibility: ["heading-relationship", "forced-colors-boundary", "logical-block-rhythm"],
  },
  {
    name: "Stack",
    role: "Vertical composition",
    purpose: "Arranges related children in one block-axis flow using gap rather than child margins.",
    whenToUse: ["Form sections", "Long compliance copy", "Vertically grouped records and metadata"],
    whenNotToUse: ["For two-dimensional peer layouts", "When source order should differ from visual order", "For arbitrary spacing values"],
    semanticElement: "Use div, ul, ol, fieldset, section, or another element that matches the child relationship.",
    classHooks: [".sk-stack", ".sk-stack-gap-sm", ".sk-stack-gap-md", ".sk-stack-gap-lg", ".sk-stack-align-start", ".sk-stack-align-center", ".sk-stack-align-stretch"],
    anatomy: [{ name: "root", purpose: "The vertical formatting context." }, { name: "items", purpose: "Direct children kept in logical reading order." }],
    variants: [{ name: "gap", values: ["sm", "md", "lg"], defaultValue: "md" }, { name: "align", values: ["start", "center", "stretch"], defaultValue: "stretch" }],
    tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-stack"], notes: "Direct children remain in source order and are separated with gap." }],
    keyboardObligations: ["Stack must not alter tab order."],
    screenReaderObligations: ["Preserve list semantics when children form a list."],
    contentRules: ["Use gap instead of child margins", "Allow long names and identifiers to wrap", "Nested stacks keep only their own selected gap"],
    motion: noMotion,
    forcedColorsBehavior: ["Stack adds no authored color or boundary."],
    mobileBehavior: ["Remains one-dimensional", "Never requires horizontal scrolling"],
    examples: [{ title: "Long-form stack", className: "sk-stack sk-stack-gap-md", markup: "<div class=\"sk-stack sk-stack-gap-md\">…</div>" }],
    galleryCoverage: ["Long compliance copy", "Nested stack", "Dense supporting facts"],
    consumerResponsibilities: ["Choose semantic list markup where applicable", "Keep children in meaningful source order"],
    accessibility: ["source-order-preserved", "long-content-safe"],
  },
  {
    name: "Cluster",
    role: "Wrapping inline composition",
    purpose: "Wraps actions, metadata, and compact facts without turning them into decorative pills.",
    whenToUse: ["Action groups", "Metadata rows", "Compact status facts"],
    whenNotToUse: ["For vertical prose", "For equal-width card grids", "To imply pill styling"],
    semanticElement: "Use div, nav, ul, or another element that represents the grouped content.",
    classHooks: [".sk-cluster", ".sk-cluster-gap-sm", ".sk-cluster-gap-md", ".sk-cluster-gap-lg", ".sk-cluster-align-start", ".sk-cluster-align-center", ".sk-cluster-align-end", ".sk-cluster-justify-start", ".sk-cluster-justify-between", ".sk-cluster-justify-end"],
    anatomy: [{ name: "root", purpose: "The wrapping inline formatting context." }, { name: "items", purpose: "Related children that may wrap to new lines." }],
    variants: [{ name: "gap", values: ["sm", "md", "lg"], defaultValue: "sm" }, { name: "align", values: ["start", "center", "end"], defaultValue: "center" }, { name: "justify", values: ["start", "between", "end"], defaultValue: "start" }],
    tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-cluster"], notes: "Items wrap naturally and keep logical source order." }],
    keyboardObligations: ["Cluster must not reorder interactive controls or change tab order."],
    screenReaderObligations: ["Use nav or list semantics only when the content relationship warrants them."],
    contentRules: ["Keep labels visible", "Allow wrapping", "Do not add pill visuals without another primitive"],
    motion: noMotion,
    forcedColorsBehavior: ["Cluster adds no authored color or boundary."],
    mobileBehavior: ["Wraps instead of overflowing", "Primary actions may become full width only in consumer composition"],
    examples: [{ title: "Action cluster", className: "sk-cluster sk-cluster-gap-sm sk-cluster-align-center", markup: "<div class=\"sk-cluster sk-cluster-gap-sm sk-cluster-align-center\">…</div>" }],
    galleryCoverage: ["Action group", "Metadata group", "Mobile wrapping"],
    consumerResponsibilities: ["Keep DOM order logical", "Choose semantic grouping markup"],
    accessibility: ["writing-mode-safe", "wrap-safe", "source-order-preserved"],
  },
  {
    name: "Grid",
    role: "Repeated peer-item composition",
    purpose: "Arranges repeated peers with one intrinsic mode and a restrained set of explicit column modes.",
    whenToUse: ["Peer evidence groups", "Repeated records", "Small directories where items share intent"],
    whenNotToUse: ["For one-dimensional actions", "As a twelve-column utility framework", "To create decorative bento layouts"],
    semanticElement: "Use ul or ol for lists; otherwise choose section or div based on the content relationship.",
    classHooks: [".sk-grid", ".sk-grid-columns-auto", ".sk-grid-columns-2", ".sk-grid-columns-3", ".sk-grid-gap-sm", ".sk-grid-gap-md", ".sk-grid-gap-lg"],
    anatomy: [{ name: "root", purpose: "The peer-item grid." }, { name: "items", purpose: "Repeated peers with independent content." }],
    variants: [{ name: "columns", values: ["auto", "2", "3"], defaultValue: "auto" }, { name: "gap", values: ["sm", "md", "lg"], defaultValue: "md" }],
    tones: [], sizes: [], requiredStates: ["default"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-grid"], notes: "The grid uses intrinsic sizing by default and collapses intentionally on narrow screens." }],
    keyboardObligations: ["Grid must not change focus order."],
    screenReaderObligations: ["Retain list semantics for repeated list items."],
    contentRules: ["Peers should share intent", "Do not make every child a Card", "Avoid arbitrary breakpoint and column APIs"],
    motion: noMotion,
    forcedColorsBehavior: ["Grid adds no authored color or boundary."],
    mobileBehavior: ["Explicit columns collapse to one", "Intrinsic mode never forces horizontal overflow"],
    examples: [{ title: "Intrinsic evidence grid", className: "sk-grid sk-grid-columns-auto sk-grid-gap-md", markup: "<ul class=\"sk-grid sk-grid-columns-auto sk-grid-gap-md\">…</ul>" }],
    galleryCoverage: ["Intrinsic peer grid", "Dense two-column workbench facts", "Narrow one-column resolution"],
    consumerResponsibilities: ["Choose semantic list markup when applicable", "Keep item order meaningful"],
    accessibility: ["source-order-preserved", "no-horizontal-overflow", "semantic-list-compatible"],
  },
] as const satisfies readonly PrimitiveContract[];
