import type { PrimitiveContract } from "./types.js";

const noMotion = { behavior: "The primitive adds no animation.", reducedMotion: "No override is required." } as const;

export const navigationDataPrimitiveSpecs = [
  {
    name: "Breadcrumb",
    role: "Current-location navigation trail", purpose: "Provides a landmark and ordered route trail with decorative separators and an unlinked current page.",
    whenToUse: ["Nested documentation", "Proof or source navigation", "Long customer routes"], whenNotToUse: ["Flat navigation", "Process steps", "JSON-LD claims"], semanticElement: "Use nav with an accessible label containing an ordered list; mark the current item aria-current=page and normally do not link it.",
    classHooks: [".sk-breadcrumb", ".sk-breadcrumb__list", ".sk-breadcrumb__item", ".sk-breadcrumb__separator"], anatomy: [{ name: "landmark", purpose: "Named breadcrumb navigation." }, { name: "ordered list", purpose: "Hierarchy order." }, { name: "item", purpose: "Route label or link." }, { name: "separator", purpose: "Decorative assistive-hidden marker." }, { name: "current page", purpose: "Unlinked current location." }], variants: [], tones: [], sizes: [], requiredStates: ["default", "long-label", "current-page"],
    stateEvidence: [{ state: "default", attributes: ["aria-label"], selectors: [".sk-breadcrumb"], notes: "Navigation landmark contains an ordered list." }, { state: "long-label", attributes: [], selectors: [".sk-breadcrumb__item"], notes: "Long labels wrap or truncate visually without changing accessible name." }, { state: "current-page", attributes: ["aria-current=page"], selectors: [".sk-breadcrumb [aria-current=\"page\"]"], notes: "Current page is programmatically exposed and not unnecessarily linked." }],
    keyboardObligations: ["Links keep native keyboard behavior", "Current page is not a redundant focus target"], screenReaderObligations: ["Name the landmark", "Use ordered list", "Hide separators", "Expose current page"], contentRules: ["Use concise route labels", "Consumer owns canonical route logic", "No schema claim"], motion: noMotion, forcedColorsBehavior: ["Links and current-page text remain distinguishable"], mobileBehavior: ["Trail wraps safely; visual truncation preserves full accessible name"], examples: [{ title: "Primitive route", className: "sk-breadcrumb", markup: "<nav class=\"sk-breadcrumb\" aria-label=\"Breadcrumb\"><ol class=\"sk-breadcrumb__list\"><li><a href=\"/\">Home</a><span class=\"sk-breadcrumb__separator\" aria-hidden=\"true\">/</span></li><li aria-current=\"page\">Primitives</li></ol></nav>" }], galleryCoverage: ["Landmark", "Ordered list", "Long label", "Current page", "Hidden separators"], consumerResponsibilities: ["Provide correct route hierarchy", "Keep current page unlinked", "Own canonical and structured-data logic"], accessibility: ["navigation-landmark", "ordered-list", "current-page", "decorative-separator-hidden"],
  },
  {
    name: "Stat",
    role: "Labelled operational value", purpose: "Presents a value with optional visible-direction delta, source/time metadata, and context without a chart or unsupported KPI certainty.",
    whenToUse: ["Operational count", "Amount", "Percentage", "Source-backed comparison"], whenNotToUse: ["Animated counters", "Unsupported KPI claims", "Charts"], semanticElement: "Use a description list or labelled figure-like group so the label clearly associates with the value.",
    classHooks: [".sk-stat", ".sk-stat__label", ".sk-stat__value", ".sk-stat__delta", ".sk-stat__meta"], anatomy: [{ name: "label", purpose: "Meaning of value." }, { name: "value", purpose: "Formatted operational value." }, { name: "delta", purpose: "Optional visible direction and amount." }, { name: "metadata", purpose: "Optional source or time." }, { name: "explanation", purpose: "Optional uncertainty or context." }], variants: [{ name: "alignment", values: ["start", "end"], defaultValue: "start" }], tones: [], sizes: [], requiredStates: ["default", "with-delta", "with-source"],
    stateEvidence: [{ state: "default", attributes: [], selectors: [".sk-stat"], notes: "Label and value are associated in source order." }, { state: "with-delta", attributes: ["data-delta-direction"], selectors: [".sk-stat__delta"], notes: "Visible words state increase or decrease; color is supporting only." }, { state: "with-source", attributes: [], selectors: [".sk-stat__meta"], notes: "Source/time remains available." }],
    keyboardObligations: ["Static Stat is not focusable."], screenReaderObligations: ["Label precedes or associates with value", "Delta direction is spoken in text"], contentRules: ["Use Indian formatters", "Use data/mono role where appropriate", "Synthetic gallery data", "No unsupported certainty", "No count-up animation"], motion: noMotion, forcedColorsBehavior: ["Value, delta wording, and boundary remain readable"], mobileBehavior: ["Long values wrap without clipping"], examples: [{ title: "Synthetic amount", className: "sk-stat", markup: "<dl class=\"sk-stat\"><dt class=\"sk-stat__label\">Synthetic amount</dt><dd class=\"sk-stat__value\">₹12,34,567.00</dd><dd class=\"sk-stat__delta\">Increase 2.4%</dd></dl>" }], galleryCoverage: ["Number", "Currency", "Percentage", "Visible-direction delta", "Source/time"], consumerResponsibilities: ["Use documented formatters", "Source claims", "Provide visible direction wording"], accessibility: ["label-value-associated", "non-color-delta", "no-count-animation"],
  },
  {
    name: "TableShell",
    role: "Semantic responsive table wrapper", purpose: "Styles native table content, density, numeric alignment, optional sticky header, and honest overflow affordance without providing data-grid behavior.",
    whenToUse: ["Tabular data requiring row/column relationships", "Dense operational amounts and dates"], whenNotToUse: ["Sorting or selection runtime", "Virtualization", "Universal row-to-card transformation", "Layout-only tables"], semanticElement: "Use a native table with caption, column headers, and row headers where appropriate inside a labelled scroll region only when overflow is genuinely necessary.",
    classHooks: [".sk-table-shell", ".sk-table-shell__viewport", ".sk-table-shell__affordance", ".sk-table-shell__numeric"], anatomy: [{ name: "shell", purpose: "Boundary and density owner." }, { name: "overflow affordance", purpose: "Visible wide-data guidance." }, { name: "viewport", purpose: "Focusable scroll region only when needed." }, { name: "table", purpose: "Native table semantics." }, { name: "caption", purpose: "Visible data-set name." }, { name: "headers", purpose: "Column and optional row relationships." }], variants: [{ name: "density", values: ["compact", "comfortable"], defaultValue: "comfortable" }, { name: "header", values: ["static", "sticky"], defaultValue: "static" }], tones: [], sizes: [], requiredStates: ["comfortable", "compact", "sticky-header", "overflow", "zoom-200", "zoom-400"],
    stateEvidence: [{ state: "comfortable", attributes: ["data-density=comfortable"], selectors: [".sk-table-shell[data-density=\"comfortable\"]"], notes: "Comfortable row floor supports longer labels." }, { state: "compact", attributes: ["data-density=compact"], selectors: [".sk-table-shell[data-density=\"compact\"]"], notes: "Compact remains readable and does not clip wrapped content." }, { state: "sticky-header", attributes: ["data-sticky-header=true"], selectors: [".sk-table-shell[data-sticky-header=\"true\"] thead"], notes: "Sticky header is opt-in." }, { state: "overflow", attributes: ["tabindex", "aria-labelledby"], selectors: [".sk-table-shell__viewport"], notes: "Visible affordance explains horizontal scrolling and focus stays visible." }, { state: "zoom-200", attributes: [], selectors: [".sk-table-shell"], notes: "Content remains reachable at 200% zoom." }, { state: "zoom-400", attributes: [], selectors: [".sk-table-shell"], notes: "Priority-data guidance prevents essential context loss at 400% zoom." }],
    keyboardObligations: ["Focusable scroll region only when overflow exists", "Focus remains visible inside viewport", "No grid keyboard model"], screenReaderObligations: ["Caption and headers required", "Use row headers where appropriate", "Name scroll region"], contentRules: ["Use Indian formatters", "Right-align numeric cells", "Use data/mono role", "Consumer owns sorting/filtering/pagination/selection", "Document mobile priority data"], motion: noMotion, forcedColorsBehavior: ["Table borders, header boundaries, and viewport focus remain visible"], mobileBehavior: ["Allow genuine horizontal overflow with visible affordance", "Do not universally transform rows into cards", "Keep priority data reachable"], examples: [{ title: "Synthetic filing amounts", className: "sk-table-shell sk-table-shell-comfortable", markup: "<div class=\"sk-table-shell sk-table-shell-comfortable\"><p id=\"filing-table-label\" class=\"sk-table-shell__affordance\">Scroll horizontally for source detail.</p><div class=\"sk-table-shell__viewport\" tabindex=\"0\" aria-labelledby=\"filing-table-label\"><table><caption>Synthetic filing amounts</caption><thead><tr><th scope=\"col\">Period</th><th scope=\"col\" class=\"sk-table-shell__numeric\">Amount</th></tr></thead><tbody><tr><th scope=\"row\">April 2026</th><td class=\"sk-table-shell__numeric\">₹12,34,567.00</td></tr></tbody></table></div></div>" }], galleryCoverage: ["Caption and headers", "Both densities", "Sticky header", "Numeric alignment", "Overflow affordance", "200% and 400% zoom", "Mobile priority guidance"], consumerResponsibilities: ["Provide semantic table markup", "Detect genuine overflow", "Own interactive behavior", "Choose priority data", "Test zoom"], accessibility: ["native-table", "caption-and-headers", "focus-visible-scroll-region", "zoom-reachable"],
  },
] as const satisfies readonly PrimitiveContract[];
