import type { PrimitiveContract } from "./types.js";

const noMotion = { behavior: "The primitive adds no animation.", reducedMotion: "No override is required." } as const;

export const processPrimitiveSpecs = [
  {
    name: "Progress",
    role: "Visible determinate or pending progress", purpose: "Styles native progress semantics and visible labels without adding runtime behavior or implying completion from motion.",
    whenToUse: ["Known determinate progress", "Meaningful bounded process"], whenNotToUse: ["Unknown background work better named pending", "Decorative completion", "Meter values"], semanticElement: "Prefer native progress with a visible label and value; consumers provide an equivalent semantic for indeterminate context when needed.",
    classHooks: [".sk-progress", ".sk-progress-indeterminate", ".sk-progress-complete", ".sk-progress-error", ".sk-progress__header", ".sk-progress__value"], anatomy: [{ name: "label", purpose: "Visible process name." }, { name: "native progress", purpose: "Determinate value semantics." }, { name: "value text", purpose: "Visible numeric or state wording." }], variants: [{ name: "state", values: ["determinate", "indeterminate", "complete", "error"], defaultValue: "determinate" }], tones: [], sizes: [], requiredStates: ["determinate", "indeterminate", "complete", "error"],
    stateEvidence: [{ state: "determinate", attributes: ["value", "max", "aria-labelledby", "aria-describedby"], selectors: [".sk-progress progress"], notes: "Native value/max and explicitly associated visible text agree." }, { state: "indeterminate", attributes: ["aria-labelledby", "aria-describedby"], selectors: [".sk-progress-indeterminate", ".sk-progress[data-progress-state=\"indeterminate\"]"], notes: "The finite class applies the state treatment; an optional data attribute can expose state evidence. Visible pending wording explains unknown completion." }, { state: "complete", attributes: ["data-progress-state=complete"], selectors: [".sk-progress-complete", ".sk-progress[data-progress-state=\"complete\"]"], notes: "Completion is stated in text." }, { state: "error", attributes: ["data-progress-state=error"], selectors: [".sk-progress-error", ".sk-progress[data-progress-state=\"error\"]"], notes: "Error appears only when semantically meaningful and includes recovery context." }],
    keyboardObligations: ["Progress itself is not interactive."], screenReaderObligations: ["Associate visible label", "Keep value and text consistent", "Do not announce cosmetic animation"], contentRules: ["Show label and value", "Use pending status when progress is unknowable", "Do not rely on meter alone"], motion: noMotion, forcedColorsBehavior: ["Native progress and visible text remain distinguishable"], mobileBehavior: ["Label and value wrap above the full-width meter"], examples: [{ title: "Determinate source check", className: "sk-progress", markup: "<div class=\"sk-progress\"><div class=\"sk-progress__header\"><span id=\"source-progress-label\">Checking sources</span><span id=\"source-progress-value\">3 of 5</span></div><progress value=\"3\" max=\"5\" aria-labelledby=\"source-progress-label\" aria-describedby=\"source-progress-value\">3 of 5</progress></div>" }], galleryCoverage: ["Determinate", "Indeterminate", "Complete", "Meaningful error", "Visible labels"], consumerResponsibilities: ["Update native values", "Choose truthful pending/error wording", "Do not claim completion prematurely"], accessibility: ["native-progress", "visible-value", "non-color-state"],
  },
  {
    name: "Stepper",
    role: "Ordered process state", purpose: "Presents process order and current/completed/upcoming state without implying navigation or beginning a product pattern.",
    whenToUse: ["Bounded ordered process", "Pack custody sequence styling"], whenNotToUse: ["Unordered status lists", "Clickable navigation without real destinations", "S7 LocalArtifactFlow"], semanticElement: "Use an ordered list; expose the current step with aria-current=step on the appropriate item or label.",
    classHooks: [".sk-stepper", ".sk-stepper__step", ".sk-stepper__marker", ".sk-stepper__label"], anatomy: [{ name: "ordered list", purpose: "Process order." }, { name: "step", purpose: "One process stage." }, { name: "marker", purpose: "Visible number or completion symbol." }, { name: "label", purpose: "Visible step state and name." }], variants: [{ name: "orientation", values: ["horizontal", "vertical"], defaultValue: "horizontal" }], tones: [], sizes: [], requiredStates: ["complete", "current", "upcoming", "blocked"],
    stateEvidence: [{ state: "complete", attributes: ["data-step-state=complete"], selectors: [".sk-stepper__step[data-step-state=\"complete\"]"], notes: "Text or symbol states completion, not color alone." }, { state: "current", attributes: ["aria-current=step"], selectors: [".sk-stepper__step[aria-current=\"step\"]"], notes: "Current step is programmatically exposed." }, { state: "upcoming", attributes: ["data-step-state=upcoming"], selectors: [".sk-stepper__step[data-step-state=\"upcoming\"]"], notes: "Upcoming is visible text or context." }, { state: "blocked", attributes: ["data-step-state=blocked"], selectors: [".sk-stepper__step[data-step-state=\"blocked\"]"], notes: "Use only when evidence requires a blocker." }],
    keyboardObligations: ["Static steps are not focusable", "Navigation exists only when consumers provide real links"], screenReaderObligations: ["Source order is process order", "Expose current step", "State is present in text"], contentRules: ["No implied clickability", "Keep custody meaning consumer-local", "Do not begin LocalArtifactFlow"], motion: noMotion, forcedColorsBehavior: ["Markers, connectors, and state text retain system-color boundaries"], mobileBehavior: ["Horizontal composition resolves to readable vertical flow without source reordering"], examples: [{ title: "Three-step review", className: "sk-stepper sk-stepper-horizontal", markup: "<ol class=\"sk-stepper sk-stepper-horizontal\"><li class=\"sk-stepper__step\" data-step-state=\"complete\">Source received — complete</li><li class=\"sk-stepper__step\" aria-current=\"step\">CA review — current</li><li class=\"sk-stepper__step\" data-step-state=\"upcoming\">Decision — upcoming</li></ol>" }], galleryCoverage: ["Complete", "Current", "Upcoming", "Evidence-backed blocked", "Mobile vertical flow"], consumerResponsibilities: ["Own process meaning", "Provide navigation only when real", "Keep state labels visible"], accessibility: ["ordered-list", "current-step", "non-color-completion"],
  },
  {
    name: "Disclosure",
    role: "Native progressive disclosure", purpose: "Styles details and summary for FAQ or simple disclosure while preserving native open/closed and keyboard behavior.",
    whenToUse: ["FAQ", "Optional technical or source detail", "Simple progressive disclosure"], whenNotToUse: ["Tabs", "Dialog", "Popover", "Nested interactive disclosure trees"], semanticElement: "Use native details and summary; associate a nearby heading when the disclosure needs section structure.",
    classHooks: [".sk-disclosure", ".sk-disclosure__summary", ".sk-disclosure__content"], anatomy: [{ name: "details", purpose: "Native open-state owner." }, { name: "summary", purpose: "Keyboard-operable accessible name." }, { name: "content", purpose: "Revealed flow content." }], variants: [], tones: [], sizes: [], requiredStates: ["closed", "open", "long-content", "nested-guidance"],
    stateEvidence: [{ state: "closed", attributes: [], selectors: [".sk-disclosure:not([open])"], notes: "Native closed state needs no script." }, { state: "open", attributes: ["open"], selectors: [".sk-disclosure[open]"], notes: "Native open state remains inspectable." }, { state: "long-content", attributes: [], selectors: [".sk-disclosure__content"], notes: "Content is not clipped by height animation." }, { state: "nested-guidance", attributes: [], selectors: [".sk-disclosure"], notes: "Avoid improperly nested interactive summaries." }],
    keyboardObligations: ["Native summary toggles with keyboard", "Do not trap focus", "Do not clip revealed focusable content"], screenReaderObligations: ["Summary is the accessible name", "Document heading relationship", "Retain native expanded state"], contentRules: ["Summary names revealed content", "Avoid nested interactive disclosures", "No Accordion runtime"], motion: { behavior: "No height animation or shared S6 motion utility.", reducedMotion: "Native state remains immediate." }, forcedColorsBehavior: ["Summary focus and disclosure boundary use system colors"], mobileBehavior: ["Summary and long content wrap without horizontal overflow"], examples: [{ title: "Open source detail", className: "sk-disclosure", markup: "<details class=\"sk-disclosure\" open><summary class=\"sk-disclosure__summary\">Source detail</summary><div class=\"sk-disclosure__content\">Synthetic reference only.</div></details>" }], galleryCoverage: ["Closed", "Open", "Long content", "Nested-content guidance"], consumerResponsibilities: ["Use native semantics", "Keep summary descriptive", "Add script only for documented unmet native need"], accessibility: ["native-details-summary", "keyboard-operable", "no-clipping-animation"],
  },
  {
    name: "CopyButton",
    role: "Explicit copy command with visible feedback", purpose: "Defines activation, success, reset, failure, disabled, and announcement obligations while leaving clipboard access in gallery or consumer code.",
    whenToUse: ["Source", "Reference", "Version", "Checksum", "Identifier"], whenNotToUse: ["Clipboard access on load", "Hidden tracking", "Copying sensitive values without context"], semanticElement: "Use a native button with an accessible name that explains the target and a separate polite status region.",
    classHooks: [".sk-copy-button", ".sk-copy-button__label", ".sk-copy-button__status"], anatomy: [{ name: "button", purpose: "Explicit activation command." }, { name: "label", purpose: "Visible default/copied/failed state." }, { name: "status", purpose: "Polite success or failure announcement." }], variants: [{ name: "state", values: ["idle", "copied", "failed"], defaultValue: "idle" }, { name: "size", values: ["sm", "md"], defaultValue: "md" }], tones: [], sizes: ["sm", "md"], requiredStates: ["idle", "copied", "failed", "disabled"],
    stateEvidence: [{ state: "idle", attributes: ["type=button"], selectors: [".sk-copy-button"], notes: "No clipboard access occurs before activation." }, { state: "copied", attributes: ["data-copy-state=copied"], selectors: [".sk-copy-button[data-copy-state=\"copied\"]"], notes: "Visible label and polite status confirm success without moving focus." }, { state: "failed", attributes: ["data-copy-state=failed"], selectors: [".sk-copy-button[data-copy-state=\"failed\"]"], notes: "Failure is visible and actionable." }, { state: "disabled", attributes: ["disabled"], selectors: [".sk-copy-button:disabled"], notes: "No-value copy is unavailable." }],
    keyboardObligations: ["Native button activation", "Focus remains on button", "No clipboard access without activation"], screenReaderObligations: ["Accessible name identifies target", "Polite status announces success/failure", "Reset does not generate unnecessary chatter"], contentRules: ["Copy appropriate reference values", "Show copied state", "Reset label after documented interval", "Failure includes manual alternative"], motion: noMotion, forcedColorsBehavior: ["Button boundary and visible state remain"], mobileBehavior: ["Label wraps and practical target remains reachable"], examples: [{ title: "Copy checksum", className: "sk-copy-button sk-size-sm", markup: "<button class=\"sk-copy-button sk-size-sm\" type=\"button\" aria-describedby=\"copy-status\">Copy checksum</button><span id=\"copy-status\" class=\"sk-copy-button__status\" role=\"status\" aria-live=\"polite\"></span>" }], galleryCoverage: ["Success", "Denied failure", "Reset", "Disabled", "Keyboard focus retained"], consumerResponsibilities: ["Call Clipboard API on activation", "Handle denial", "Reset label", "Keep focus", "Avoid sensitive copy"], accessibility: ["explicit-activation", "focus-retained", "visible-and-announced-feedback"],
  },
] as const satisfies readonly PrimitiveContract[];
