import type { PrimitiveContract } from "./types.js";

const noMotion = { behavior: "The primitive adds no motion.", reducedMotion: "No override is required." } as const;

export const statePrimitiveSpecs = [
  {
    name: "Skeleton",
    role: "Layout-preserving loading placeholder", purpose: "Preserves approximate layout during a truthful loading context without implying that content is loaded, verified, or complete.",
    whenToUse: ["Known content layout is loading", "Short loading state where spatial continuity helps"], whenNotToUse: ["Unknown background work", "Where Loading… is more truthful", "Decorative perpetual motion"],
    semanticElement: "Place aria-busy on the owning region; skeleton shapes are normally aria-hidden and have no role.", classHooks: [".sk-skeleton", ".sk-skeleton-text", ".sk-skeleton-block", ".sk-skeleton-row", ".sk-skeleton-avatar"],
    anatomy: [{ name: "owning region", purpose: "Consumer region carrying aria-busy." }, { name: "shape", purpose: "Assistive-hidden layout placeholder." }], variants: [{ name: "form", values: ["text", "block", "row", "avatar"], defaultValue: "text" }], tones: [], sizes: [],
    requiredStates: ["loading", "reduced-motion", "forced-colors"], stateEvidence: [{ state: "loading", attributes: ["aria-busy", "aria-hidden"], selectors: [".sk-skeleton"], notes: "Owning region is busy; shapes are hidden from assistive technology." }, { state: "reduced-motion", attributes: [], selectors: [".sk-skeleton"], notes: "Nonessential animation is disabled." }, { state: "forced-colors", attributes: [], selectors: [".sk-skeleton"], notes: "Outline remains without a misleading filled surface." }],
    keyboardObligations: ["Skeleton shapes are never focusable."], screenReaderObligations: ["Use aria-busy on owner", "Hide decorative shapes", "Provide truthful loading text when needed"], contentRules: ["Approximate layout", "Do not imply verified content", "Use only inside loading context", "Avatar form requires real consumer evidence"],
    motion: { behavior: "A local token-driven pulse may indicate loading; no shared S6 utility is exported.", reducedMotion: "Animation is removed and the static outline remains." }, forcedColorsBehavior: ["CanvasText outline remains; filled shimmer is removed"], mobileBehavior: ["Shapes stay within available width and avoid layout shift"], examples: [{ title: "Busy review row", className: "sk-skeleton sk-skeleton-row", markup: "<section aria-busy=\"true\" aria-label=\"Loading review rows\"><div class=\"sk-skeleton sk-skeleton-row\" aria-hidden=\"true\"></div></section>" }], galleryCoverage: ["Text, block, row", "Owning aria-busy region", "Reduced motion", "Forced colors"], consumerResponsibilities: ["Own aria-busy and loading label", "Replace placeholders with real content", "Avoid uncontrolled layout shift"], accessibility: ["owner-busy", "shape-hidden", "nonanimated-reduced-motion"],
  },
  {
    name: "EmptyState",
    role: "Guided absence and next action", purpose: "Explains why useful content is absent and provides an appropriate next action without an implicit alert.",
    whenToUse: ["Truly empty collection", "Filtered no-results", "Permission or source gap"], whenNotToUse: ["Errors requiring recovery", "Decorative sadness", "Generic Nothing here copy"], semanticElement: "Use a section or aside with a labelled heading; actions remain native Link or Button semantics.",
    classHooks: [".sk-empty-state", ".sk-empty-state-filtered", ".sk-empty-state-unavailable", ".sk-empty-state__marker", ".sk-empty-state__actions", ".sk-empty-state__detail"], anatomy: [{ name: "title", purpose: "Names the absence." }, { name: "explanation", purpose: "Explains cause or boundary." }, { name: "primary action", purpose: "Clear next step." }, { name: "detail", purpose: "Optional secondary or source detail." }, { name: "marker", purpose: "Optional restrained visual cue." }], variants: [{ name: "kind", values: ["empty", "filtered", "unavailable"], defaultValue: "empty" }], tones: [], sizes: [], requiredStates: ["empty", "filtered", "unavailable"],
    stateEvidence: [{ state: "empty", attributes: [], selectors: [".sk-empty-state"], notes: "Explains how to create or obtain the first item." }, { state: "filtered", attributes: ["data-empty-kind=filtered"], selectors: [".sk-empty-state-filtered", ".sk-empty-state[data-empty-kind=\"filtered\"]"], notes: "The finite class applies the variant styling; an optional data attribute can expose state evidence. Provide an explicit reset action." }, { state: "unavailable", attributes: ["data-empty-kind=unavailable"], selectors: [".sk-empty-state-unavailable", ".sk-empty-state[data-empty-kind=\"unavailable\"]"], notes: "The finite class applies the variant styling; an optional data attribute can expose state evidence. Name the permission or source gap without blaming the user." }],
    keyboardObligations: ["Actions keep native Link or Button behavior."], screenReaderObligations: ["Use a labelled region where helpful", "Do not add alert role by default"], contentRules: ["Distinguish empty, filtered, and unavailable", "State the next action", "No illustration substitutes for guidance"], motion: noMotion, forcedColorsBehavior: ["Text, marker, and action boundaries remain visible"], mobileBehavior: ["Copy stays concise and actions wrap or stack"], examples: [{ title: "Filtered result", className: "sk-empty-state sk-empty-state-filtered", markup: "<section class=\"sk-empty-state sk-empty-state-filtered\"><h3>No matching tools</h3><p>Clear the search to restore all tools.</p><button type=\"button\">Reset search</button></section>" }], galleryCoverage: ["True empty", "Filtered reset", "Permission/source unavailable"], consumerResponsibilities: ["Choose truthful kind", "Wire actions", "Use native action semantics"], accessibility: ["clear-heading", "explicit-next-action", "no-implicit-alert"],
  },
  {
    name: "ErrorState",
    role: "Recoverable failure explanation", purpose: "Names a failure, preserves source or reference context, and exposes explicit recovery without blame or false certainty.",
    whenToUse: ["Recoverable operation failure", "Synthetic copy or network failure", "Support/reference handoff"], whenNotToUse: ["Field-level validation", "Raw stack traces", "Errors with no recovery information"], semanticElement: "Use a labelled section; dynamic errors may use alert or status when context requires it, without moving focus automatically.",
    classHooks: [".sk-error-state", ".sk-error-state-blocking", ".sk-error-state__actions", ".sk-error-state__reference", ".sk-error-state__details"], anatomy: [{ name: "title", purpose: "Names the failure." }, { name: "explanation", purpose: "Explains what is known." }, { name: "recovery action", purpose: "Explicit retry or safe next step." }, { name: "support action", purpose: "Optional support path." }, { name: "reference", purpose: "Optional source or reference ID." }, { name: "technical detail", purpose: "Optional native disclosure." }], variants: [{ name: "severity", values: ["recoverable", "blocking"], defaultValue: "recoverable" }], tones: [], sizes: [], requiredStates: ["recoverable", "blocking", "with-details"],
    stateEvidence: [{ state: "recoverable", attributes: [], selectors: [".sk-error-state"], notes: "Retry is an explicit command." }, { state: "blocking", attributes: ["data-error-severity=blocking"], selectors: [".sk-error-state-blocking", ".sk-error-state[data-error-severity=\"blocking\"]"], notes: "The finite class applies the variant styling; an optional data attribute can expose state evidence. Visible copy names the safe next step." }, { state: "with-details", attributes: [], selectors: [".sk-error-state__details"], notes: "Technical detail uses native disclosure and no public stack trace." }],
    keyboardObligations: ["Retry and support actions use native controls", "Dynamic errors do not steal focus"], screenReaderObligations: ["Choose alert/status only for actual dynamic context", "Keep reference and recovery in reading order"], contentRules: ["No blame", "No false certainty", "No raw public stack trace", "Use synthetic examples", "Reference IDs use data/mono role"], motion: noMotion, forcedColorsBehavior: ["Boundary, wording, and actions remain visible"], mobileBehavior: ["Actions wrap and details remain reachable"], examples: [{ title: "Recoverable copy failure", className: "sk-error-state", markup: "<section class=\"sk-error-state\"><h3>Could not copy the reference</h3><p>Copy it manually or try again.</p><button type=\"button\">Try again</button><p class=\"sk-error-state__reference\">Reference COPY-EXAMPLE-01</p></section>" }], galleryCoverage: ["Retry", "Support", "Reference ID", "Technical disclosure", "Synthetic copy and network failures"], consumerResponsibilities: ["Choose announcement semantics", "Implement retry", "Sanitize technical detail", "Preserve focus"], accessibility: ["explicit-recovery", "focus-not-stolen", "contextual-announcement"],
  },
] as const satisfies readonly PrimitiveContract[];
